DiplomMSSQLApp.WEB/Models/BusinessTripViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DiplomMSSQLApp.WEB.Models
{
    public class BusinessTripViewModel : BaseBusinessTripViewModel {
        [Display(Name = "Список сотрудников")]
        public virtual ICollection<EmployeeViewModel> Employees { get; set; }

        public BusinessTripViewModel()
        {
            Employees = new List<EmployeeViewModel>();
        }
    }
}

DiplomMSSQLApp.WEB/Controllers/BusinessTripController.cs
using AutoMapper;
using DiplomMSSQLApp.BLL.BusinessModels;
using DiplomMSSQLApp.BLL.DTO;
using DiplomMSSQLApp.BLL.Infrastructure;
using DiplomMSSQLApp.BLL.Interfaces;
using DiplomMSSQLApp.BLL.Services;
using DiplomMSSQLApp.WEB.Models;
using DiplomMSSQLApp.WEB.Util;
using NLog;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DiplomMSSQLApp.WEB.Controllers {
    [HandleError]
    [Authorize]
    [Internationalization]
    public class BusinessTripController : Controller {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
        private IService<BusinessTripDTO> _businessTripService;
        private IService<EmployeeDTO> _employeeService;

        public BusinessTripController(IService<BusinessTripDTO> bs, IService<EmployeeDTO> es) {
            _businessTripService = bs;
            _employeeService = es;
        }

        public ActionResult Index(BusinessTripFilter filter, string filterAsJsonString, int page = 1) {
            if (filterAsJsonString != null)
                filter = System.Web.Helpers.Json.Decode<BusinessTripFilter>(filterAsJsonString);
            IEnumerable<BusinessTripDTO> btDto = (_businessTripService as BusinessTripService).Get(filter);  // Filter
            btDto = _businessTripService.GetPage(btDto, page);     // Paging
            Mapper.Initialize(cfg => cfg.CreateMap<BusinessTripDTO, BusinessTripViewModel>()
                                        .ForMember(bt => bt.Employees, opt => opt.Ignore()));
            IEnumerable<BusinessTripViewModel> businessTrips = Mapper.Map<IEnumerable<BusinessTripDTO>, IEnumerable<BusinessTripViewModel>>(btDto);
            BusinessTripListViewModel model = new BusinessTripListViewModel {
                BusinessTrips = businessTrips,
                Filter = filter,
                PageInfo = _businessTripService.PageInfo
            };
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest") {
                _logger.Info("Executed async request");
                var transformModel = new {
                    BusinessTrips = model.BusinessTrips.Select(bt => new {
                        bt.Id,
                        Code = bt.Name,
                        DateStart = bt.DateStart.ToString("dd MMMM yyyy"),
                        DateEnd = bt.DateEnd.ToString("dd MMMM yyyy"),
                        bt.Destination
                    }).ToArray(),
                    model.Filter,
                    model.PageInfo
                };
                return Json(transformModel, JsonRequestBehavior.AllowGet);
            }
            _logger.Info("Executed sync request");
            return View("Index", model);
        }

        // Добавление новой командировки
        public async Task<ActionResult> Create() {
            int employeesCount = await _employeeService.CountAsync();
            if (employeesCount == 0) {
                _logger.Warn("No employees");
                return View("Error", new string[] { "В организации нет сотрудников" });
            }
            ViewBag.Employees = await GetSelectListEmployeesAsync();
            return View("Create");
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(BusinessTripViewModel bt) {
            try {
                BusinessTripDTO btDto = MapViewModelWithDTO(bt);
                await (_businessTripService as BusinessTripService).CreateAsync(btDto);
                return RedirectToAction("Index");
            }
            catch (ValidationException ex) {
                _logger.Warn(ex.Message);
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            ViewBag.Employees = await GetSelectListEmployeesAsync();
            return View("Create", bt);
        }

        private async Task<SelectList> GetSelectListEmployeesAsync() {
            IEnumerable<EmployeeDTO> employees = await _employeeService.GetAllAsync();
            IEnumerable<SelectListItem> items = employees.Select(e => new SelectListItem() {
                Value = e.Id.ToString(),
                Text = new System.Text.StringBuilder(e.LastName).Append(" ").Append(e.FirstName).Append(" ")
                    .Append(e.Patronymic ?? "").Append(" [").Append(e.Post.Department.DepartmentName).Append("]").ToString()
            }).OrderBy(e => e.Text);
            return new SelectList(items, "Value", "Text");
        }

        private BusinessTripDTO MapViewModelWithDTO(BusinessTripViewModel bt) {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<BusinessTripViewModel, BusinessTripDTO>();
                cfg.CreateMap<EmployeeViewModel, EmployeeDTO>()
                    .ForMember(e => e.AnnualLeaves, opt => opt.Ignore())
                    .ForMember(e => e.Birth, opt => opt.Ignore())
                    .ForMember(e => e.BusinessTrips, opt => opt.Ignore())
                    .ForMember(e => e.Contacts, opt => opt.Ignore())
                    .ForMember(e => e.Education, opt => opt.Ignore())
                    .ForMember(e => e.Passport, opt => opt.Ignore())
                    .ForMember(e => e.Post, opt => opt.Ignore());
            });
            BusinessTripDTO btDto = Mapper.Map<BusinessTripViewModel, BusinessTripDTO>(bt);
            return btDto;
        }

        // Обновление информации о командировке
        public async Task<ActionResult> Edit(int? id) {
            ViewBag.Employees = await GetSelectListEmployeesAsync();
            return await GetViewAsync(id, "Edit");
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(BusinessTripViewModel bt) {
            try {
                BusinessTripDTO btDto = MapViewModelWithDTO(bt);
                await (_businessTripService as BusinessTripService).EditAsync(btDto);
                return RedirectToAction("Index");
            }
            catch (ValidationException ex) {
                _logger.Warn(ex.Message);
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            ViewBag.Employees = await GetSelectListEmployeesAsync();
            return View("Edit", bt);
        }

        private async Task<ActionResult> GetViewAsync(int? id, string viewName) {
            try {
                BusinessTripDTO btDto = await _businessTripService.FindByIdAsync(id);
                BusinessTripViewModel bt = MapDTOWithViewModel(btDto);
                return View(viewName, bt);
            }
            catch (ValidationException ex) {
                _logger.Warn(ex.Message);
                return View("Error", new string[] { ex.Message });
            }
        }

        private BusinessTripViewModel MapDTOWithViewModel(BusinessTripDTO btDTO) {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<BusinessTripDTO, BusinessTripViewModel>();
                cfg.CreateMap<EmployeeDTO, EmployeeViewModel>()
                    .ForMember(e => e.AnnualLeaves, opt => opt.Ignore())
                    .ForMember(e => e.Birth, opt => opt.Ignore())
                    .ForMember(e => e.BusinessTrips, opt => opt.Ignore())
                    .ForMember(e => e.Contacts, opt => opt.Ignore())
                    .ForMember(e => e.Education, opt => opt.Ignore())
                    .ForMember(e => e.Passport, opt => opt.Ignore())
                    .ForMember(e => e.Post, opt => opt.Ignore());
            });
            BusinessTripViewModel bt = Mapper.Map<BusinessTripDTO, BusinessTripViewModel>(btDTO);
            return bt;
        }

        // Подробная информация о командировке
        public async Task<ActionResult> Details(int? id) {
            return await GetViewAsync(id, "Details");
        }

        // Удаление командировки
        public async Task<ActionResult> Delete(int? id) {
            return await GetViewAsync(id, "Delete");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id) {
            await _businessTripService.DeleteAsync(id);
            return RedirectToAction("Index");
        }

        // Удаление всех командировок
        public ActionResult DeleteAll() {
            return View("DeleteAll");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("DeleteAll")]
        public async Task<ActionResult> DeleteAllConfirmed() {
            await _businessTripService.DeleteAllAsync();
            return RedirectToAction("Index");
        }

        // Запись информации о командировках в JSON-файл
        public async Task<ActionResult> ExportJson() {
            string fullPath = CreateDirectoryToFile("BusinessTrips.json");
            System.IO.File.Delete(fullPath);
            await _businessTripService.ExportJsonAsync(fullPath);
            return File(fullPath, "application/json", "BusinessTrips.json");
        }

        private string CreateDirectoryToFile(string filename) {
            string dir = Server.MapPath("~/Results/");
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            string fullPath = dir + filename;
            return fullPath;
        }

        // Добавление командировок для тестирования
        public async Task<ActionResult> TestCreate() {
            try {
                await (_businessTripService as BusinessTripService).TestCreateAsync();
            }
            catch (ValidationException ex) {
                _logger.Warn("No employees");
                return View("Error", new string[] { ex.Message });
            }
            return RedirectToAction("Index");
        }

        // Частичное представление добавляет выпадающий список сотрудников
        public async Task<ActionResult> AddEmployeeAsync(int index) {
            ViewBag.Index = index;
            ViewBag.Employees = await GetSelectListEmployeesAsync();

DiplomMSSQLApp.WEB/Views/BusinessTrip/AddEmployee.cshtml
@{
    int i = ViewBag.Index;
}

<div class="form-group">
    @Html.Label("Employees[" + i + "].Id", "Сотрудник №" + (i + 1).ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("Employees[" + i + "].Id", ViewBag.Employees as SelectList, new { @class = "form-control" })
        @Html.ValidationMessage("Employees[" + i + "].Id", "", new { @class = "text-danger" })
    </div>
</div>

DiplomMSSQLApp.WEB/Views/BusinessTrip/Create.cshtml
@model DiplomMSSQLApp.WEB.Models.BusinessTripViewModel

@{
    ViewBag.Title = "Добавление командировки";
}

<h2>Добавление командировки</h2>
<hr />

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purpose, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purpose, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purpose, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="employees">
            <div class="employee0">
                <div class="form-group">
                    @Html.Label("Employees[0].Id", "Сотрудник №1", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Employees[0].Id", ViewBag.Employees as SelectList, new { @class = "form-control" })
                        @Html.ValidationMessage("Employees[0].Id", "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <p><a id="addEmployee">Добавить сотрудника</a></p>
        <p><a id="deleteEmployee">Удалить сотрудника</a></p>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-primary" />
                @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            var i = 0;
            // Добавление сотрудника
            $('#addEmployee').click(function (e) {
                e.preventDefault();
                i++;
                var div = document.createElement('div');
                div.className = "employee" + i.toString();
                $('.employees').append(div);
                $('.employee' + i.toString()).load('@Url.Action("AddEmployeeAsync", "BusinessTrip")?index=' + i)
            });
            // Удаление сотрудника
            $('#deleteEmployee').click(function (e) {
                e.preventDefault();
                if (i > 0) {
                    $('.employee' + i.toString()).remove();
                    i--;
                }
            });
        });
    </script>
}

DiplomMSSQLApp.WEB/Views/BusinessTrip/Delete.cshtml
@model DiplomMSSQLApp.WEB.Models.BusinessTripViewModel

@{
    ViewBag.Title = "Удаление командировки";
}

<h2>Удаление командировки</h2>
<hr />

<h3>Вы уверены, что хотите удалить командировку?</h3>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateStart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purpose)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Purpose)
        </dd>

        @for (int i = 0; i < Model.Employees.Count; i++) {
            <dt>
                @Html.Label("Employee", "Сотрудник №" + (i + 1).ToString())
            </dt>
            <dd>
                @Model.Employees.ElementAt(i).LastName
                @Model.Employees.ElementAt(i).FirstName
            </dd>
        }
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-primary" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

DiplomMSSQLApp.WEB/Views/BusinessTrip/DeleteAll.cshtml
@{
    ViewBag.Title = "Удаление всех командировок";
}

<h2>Удаление всех командировок</h2>
<hr />

<h4>Вы уверены, что хотите удалить все командировки?</h4>
<br />

<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-primary" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

DiplomMSSQLApp.WEB/Views/BusinessTrip/Details.cshtml
@model DiplomMSSQLApp.WEB.Models.BusinessTripViewModel

@{
    ViewBag.Title = "Подробная информация о командировке";
}

<h2>Подробная информация о командировке</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateStart)
        </dt>
        <dd>
            @Model.DateStart.ToString("dd MMMM yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd>
            @Model.DateEnd.ToString("dd MMMM yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purpose)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Purpose)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employees)
        </dt>
        @if (Model.Employees != null) {
            foreach (var item in Model.Employees) {
                <dd>
                    @item.LastName
                    @item.FirstName
                    @item.Patronymic
                </dd>
            }
        }
    </dl>
</div>
<br />
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
</p>

DiplomMSSQLApp.WEB/Views/BusinessTrip/Edit.cshtml
@model DiplomMSSQLApp.WEB.Models.BusinessTripViewModel

@{
    ViewBag.Title = "Обновление информации о командировке";
}

<h2>Обновление информации о командировке</h2>
<hr />

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateStart, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.DateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateEnd, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Purpose, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purpose, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purpose, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="employees">
            @for (int i = 0; i < Model.Employees.Count; i++) {
                string str = "employee" + i.ToString();
                <div class=@str>
                    <div class="form-group">
                        @Html.Label("Employees[" + i + "].Id", "Сотрудник №" + (i + 1).ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Employees[" + i + "].Id", ViewBag.Employees as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessage("Employees[" + i + "].Id", "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
        
        <p><a id="addEmployee">Добавить сотрудника</a></p>
        <p><a id="deleteEmployee">Удалить сотрудника</a></p>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Обновить" class="btn btn-primary" />
                @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            var i = @Model.Employees.Count -1;
            // Добавление сотрудника
            $('#addEmployee').click(function (e) {
                e.preventDefault();
                i++;
                var div = document.createElement('div');
                div.className = "employee" + i.toString();
                $('.employees').append(div);
                $('.employee' + i.toString()).load('@Url.Action("AddEmployeeAsync", "BusinessTrip")?index=' + i)
            });
            // Удаление сотрудника
            $('#deleteEmployee').click(function (e) {
                e.preventDefault();
                if (i > 0) {
                    $('.employee' + i.toString()).remove();
                    i--;
                }
            });
            // Устанавливаем начальные значения для DropDownList
            @for (int i = 0; i < @Model.Employees.Count; i++) {
                int id = Model.Employees.ElementAt(i).Id;
                @:$("select#Employees_@(i)__Id option[value='@id']").prop('selected', true);
            }
        });
    </script>
}