DiplomMSSQLApp.WEB/Controllers/RoleAdminController.cs
using DiplomMSSQLApp.WEB.Infrastructure;
using DiplomMSSQLApp.WEB.Models.Identity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NLog;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DiplomMSSQLApp.WEB.Controllers {
    [HandleError]
    [Authorize(Roles = "Administrators")]
    public class RoleAdminController : Controller {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
        private AppUserManager _userManager;
        private AppRoleManager _roleManager;

        private AppUserManager UserManager {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<AppUserManager>(); }
            set { _userManager = value; }
        }

        private AppRoleManager RoleManager {
            get { return _roleManager ?? HttpContext.GetOwinContext().GetUserManager<AppRoleManager>(); }
            set { _roleManager = value; }
        }

        public RoleAdminController() { }

        public RoleAdminController(AppUserManager userManager, AppRoleManager roleManager) {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        /// <summary>
        /// // Index method
        /// </summary>
        public ActionResult Index() {
            return View("Index", RoleManager.Roles);
        }

        /// <summary>
        /// // Create method
        /// </summary>
        public ActionResult Create() {
            return View("Create");
        }
        [HttpPost]
        public async Task<ActionResult> Create([Required]string name) {
            if (ModelState.IsValid) {
                IdentityResult result = await RoleManager.CreateAsync(new AppRole(name));
                if (result.Succeeded) {
                    _logger.Info("Succeeded");
                    return RedirectToAction("Index");
                }
                else {
                    foreach (string error in result.Errors) {
                        _logger.Warn(error);
                        ModelState.AddModelError("", error);
                    }
                    return View("Create", name);
                }
            }
            _logger.Warn("ModelState is invalid");
            return View("Create", name);
        }

        /// <summary>
        /// // Edit method
        /// </summary>
        public async Task<ActionResult> Edit(string id) {
            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role == null) {
                _logger.Warn("Role not found");
                return View("Error", new string[] { "Роль не найдена" });
            }
            string[] memberIDs = role.Users.Select(x => x.UserId).ToArray();
            IEnumerable<AppUser> members = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<AppUser> nonMembers = UserManager.Users.Except(members);
            return View("Edit", new RoleEditModel {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationModel model) {
            IdentityResult result;
            if (ModelState.IsValid) {
                foreach (string userId in model.IdsToAdd ?? new string[] { }) {
                    result = await UserManager.AddToRoleAsync(userId, model.RoleName);
                    if (!result.Succeeded) {
                        foreach (string error in result.Errors) {
                            _logger.Warn(error);
                        }
                        return View("Error", result.Errors);
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { }) {
                    result = await UserManager.RemoveFromRoleAsync(userId, model.RoleName);
                    if (!result.Succeeded) {
                        foreach (string error in result.Errors) {
                            _logger.Warn(error);
                        }
                        return View("Error", result.Errors);
                    }
                }
                _logger.Info("Succeeded");
                return RedirectToAction("Index");
            }
            _logger.Warn("Role not found");
            return View("Error", new string[] { "Роль не найдена" });
        }

        /// <summary>
        /// // Delete method
        /// </summary>
        [HttpPost]
        public async Task<ActionResult> Delete(string id) {
            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role != null) {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded) {
                    _logger.Info("Succeeded");
                    return RedirectToAction("Index");
                }
                else {
                    foreach (string error in result.Errors) {
                        _logger.Warn(error);
                    }
                    return View("Error", result.Errors);
                }
            }
            else {
                _logger.Warn("Role not found");
                return View("Error", new string[] { "Роль не найдена" });
            }
        }
    }
}

DiplomMSSQLApp.WEB/Views/RoleAdmin/Create.cshtml
@model string

@{
    ViewBag.Title = "Добавление роли";
}

<h2>Добавление роли</h2>
<hr />

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@using (Html.BeginForm()) {
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control" />
        @Html.ValidationMessageFor(model => model, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Добавить</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

DiplomMSSQLApp.WEB/Views/RoleAdmin/Edit.cshtml
@using DiplomMSSQLApp.WEB.Models.Identity
@model RoleEditModel

@{
    ViewBag.Title = "Редактирование роли";
}

<h2>Редактирование роли @Model.Role.Name</h2>
<hr />

@Html.ValidationSummary()
@using (Html.BeginForm()) {
    <input type="hidden" name="roleName" value="@Model.Role.Name" />

    <h4>Добавить роль</h4>
    <table class="table table-striped">
        @if (Model.NonMembers.Count() == 0) {
            <tr>
                <td colspan="2">Все пользователи являются членами роли</td>
            </tr>
        }
        else {
            <tr>
                <td>Name</td>
                <td>Add To Role</td>
            </tr>
            foreach (AppUser user in Model.NonMembers) {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToAdd" value="@user.Id">
                    </td>
                </tr>
            }
        }
    </table>
    <hr />
    <h4>Удалить роль</h4>
    <table class="table table-striped">
        @if (Model.Members.Count() == 0) {
            <tr>
                <td colspan="2">Ни один пользователь не является членом роли</td>
            </tr>
        }
        else {
            <tr>
                <td>Name</td>
                <td>Remove From Role</td>
            </tr>
            foreach (AppUser user in Model.Members) {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToDelete" value="@user.Id">
                    </td>
                </tr>
            }
        }
    </table>

    <button type="submit" class="btn btn-primary">Сохранить</button>
    @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
}

DiplomMSSQLApp.WEB/Views/RoleAdmin/Index.cshtml
@using DiplomMSSQLApp.WEB.Models.Identity
@using DiplomMSSQLApp.WEB.Infrastructure
@model IEnumerable<AppRole>

@{
    ViewBag.Title = "Роли";
}

<h2>Роли</h2>
<hr />

<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Users</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0) {
        <tr>
            <td colspan="3" class="text-center">Нет ролей</td>
        </tr>
    }
    else {
        foreach (AppRole role in Model) {
            <tr>
                <td>@role.Name</td>
                <td>
                    @if (role.Users == null || role.Users.Count == 0) {
                        @: Нет пользователей в данной роли
                    }
                    else {
                        <p>
                            @string.Join(", ", role.Users.Select(x => Html.GetUserName(x.UserId)))
                        </p>
                    }
                </td>
                <td>
                    @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id })) {
                        @Html.ActionLink("Изменить", "Edit", new { id = role.Id }, new { @class = "btn btn-primary btn-xs" })
                        <button class="btn btn-danger btn-xs" type="submit">Удалить</button>
                    }
                </td>
            </tr>
        }
    }
</table>

@Html.ActionLink("Добавить", "Create", null, new { @class = "btn btn-primary" })